library("sqldf")
stu<-read.csv(file.choose())
stu
View(sqldf("select * from stu"))
sqldf("select count (*) from stu")
sqldf("select * from stu where marks>80")
sqldf("select *from stu where marks<80")
sqldf("select * from stu where name=='Veer'")
sqldf("select * from stu where marks==45")
sqldf("select name from stu where marks==45")
sqldf("select distinct name from stu")
sqldf("select * from stu limit 2")
sqldf("select * from stu order by name desc")
sqldf("select * from stu where name like '%s'")
sqldf("select * from stu where name like 'V%'")
sqldf("select * from stu where name like '%k%'")
sqldf("select name as N, marks as M from stu")
sqldf("select sum(marks)from stu")
sqldf("select avg(marks) from stu")
sqldf("select min(marks) from stu")
sqldf("select max(marks) from stu")
nrow(stu)
ncol(stu)
